# Generated by Django 3.2.3 on 2021-05-31 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moozy_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_registration_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=500, verbose_name='Restaurant Name')),
                ('registration_type', models.CharField(max_length=100, verbose_name='Registration Type')),
                ('name_of_proprietor', models.CharField(max_length=100, verbose_name='Proprietor Name')),
                ('manager_name', models.CharField(max_length=100, verbose_name='Manager Name')),
                ('pan_number', models.CharField(max_length=20, verbose_name='Pan Card')),
                ('address', models.CharField(max_length=1000, verbose_name='address')),
                ('gst_no', models.CharField(max_length=30, verbose_name='GST No.')),
                ('gst_rate', models.IntegerField(verbose_name='GST Rate(%)')),
                ('fssai_no', models.CharField(max_length=14, verbose_name='FSSAI No.')),
                ('mobile_no', models.CharField(max_length=12, verbose_name='Mobile No.')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('bank_ac_no', models.CharField(max_length=25, verbose_name='Bank Account No.')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('ifsc_code', models.CharField(max_length=50, verbose_name='IFSC Code')),
                ('km_range', models.IntegerField(verbose_name='Range in Km')),
                ('active_since', models.DateField(verbose_name='Active Since')),
                ('daily_working_time', models.TimeField(verbose_name='Restaurant Open(Morning)')),
                ('daily_off', models.TimeField(verbose_name='Restaurant Close(Morning')),
                ('evening_timeo', models.TimeField(verbose_name='Restaurant Open(Evening')),
                ('evening_timec', models.TimeField(verbose_name='Restaurant Close(Evening)')),
                ('restaurant_type', models.CharField(choices=[('Veg', 'Veg'), ('Nonveg', 'Nonveg'), ('Both', 'Both')], max_length=20, verbose_name='Restaurant Type')),
                ('special_item', models.CharField(max_length=100, verbose_name='Special Type')),
                ('registration_date', models.DateTimeField()),
                ('res_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantuser', to=settings.AUTH_USER_MODEL, verbose_name='Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('availability', models.BooleanField(default=True)),
                ('res_att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attcat', to='moozy_admin.attributecategory', verbose_name='Select Attribute')),
                ('res_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restarantuser', to=settings.AUTH_USER_MODEL, verbose_name='Restaurant')),
                ('rescat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catag', to='moozy_admin.foodcategory', verbose_name='Select Category')),
                ('resmenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='men', to='moozy_admin.menu', verbose_name='Select Item')),
            ],
        ),
    ]
